//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Multifuncional.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia_miembro
    {
        public int id { get; set; }
        public int miembro { get; set; }
        public int materia { get; set; }
    
        public virtual materia materia1 { get; set; }
        public virtual miembro miembro1 { get; set; }
    }
}
